- package-lock.json
- package.json
- src/app/api/getTransactionInfo/route.js
- src/app/api/loadSupportRegion/route.js
- src/app/api/loadWalletByCurrency/route.js
- src/app/api/submitPayment/route.js
- src/app/utilites/db.js
Case 1: Currency Code Available
Case 2 : No Currency Code Available 
Load all SupportRegion
> [API] Load Wallet by Currency Code and Load Support Region  are added

- src/app/api/submitPayment/route.js
Case 1: Without ScreenShot => return error and exit  
Case 2: With Screenshot => added Data in database tables
> [API] Added screenshot in submitpayment api

- .gitignore
- src/app/HomePage.js
- src/app/UI/CreateForm.js
- src/app/UI/ExtendUser/ExtendUserForm.js
- src/app/api/checkAgent/route.js
- src/app/api/createAgent/route.js
- src/app/api/loadWalletByCurrency/route.js
- src/app/api/submitPayment/route.js
- src/app/utilites/createForm/createformSubmit.js
- src/app/utilites/getAuthCurrentUser.js
[Bug] Cannot submit form => Data is not imported to database table. 
Estimated area might be in /utlities/createForm/createformsubmit => bug between calling api and json data input.
> [Backend] checkAgent, createAgent , Standardize Format and Wallets,SupportRegions integrate with frontend  

- src/app/UI/CreateForm.js
- src/app/api/submitPayment/route.js
- src/app/api/transactions/route.js
- src/app/utilites/createForm/fileHandler.js
extract Data from database by Payment Check (1 | 0) 
1 => true , 0 => false
> [API] fetch table Data by paymentCheck 

- src/app/UI/CreateForm.js
- src/app/api/checkAgent/route.js
- src/app/api/submitPayment/route.js
- src/app/utilites/createForm/createformSubmit.js
- src/app/utilites/db.js
I fixed Transaction submission on first time when database or server starts which didn't work .
> [Bug] fix for firstTime Transaction

- .idea/.gitignore
- .idea/hope-fuel.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- development.sql
- src/app/UI/PaymentTeam/PaymentTeam.js
- src/app/api/submitPayment/route.js
- src/app/api/transactions/route.js
I fixed for the transaction form submission  required field for contactLink and Note if they are blank.
> [Bug] fix require field

- src/app/UI/PaymentTeam/PaymentTeam.js
- src/app/api/paymentConfirmOrDeined/route.js
- src/app/api/submitPayment/route.js
- src/app/api/transactions/route.js
[Bug Fix +DB new column] HopeFuelID in DB and Payment check bug fix
> [Bug Fix +DB new column] HopeFuelID in DB and Payment check bug fix

- src/app/HomePage.js
- src/app/UI/AppBar/AppBar.js
- src/app/UI/ExtendForm.js
- src/app/UI/ExtendUser/ExtendUserForm.js
- src/app/utilites/ExtendUser/extendUserSubmit.js
[BugFix] ExtendUser keep crash if agentId is not requested.
[BugFix] Agent ID not record for old customer in TransactionsAgent Table.
> [BugFix] Fix transaction agent

- src/app/UI/ExtendUser/ExtendUserForm.js
The timer from the extendUser component is making the error of not getting the agentID for the form
> remove the timer

- src/app/HomePage.js
- src/app/UI/AppBar/AppBar.js
- src/app/UI/Components/ItemCard.js
- src/app/UI/Components/ItemList.js
- src/app/UI/Components/SearchBar.js
- src/app/UI/SearchForm/searchPage.js
- src/app/api/searchDB/route.js
- src/app/api/submitPayment/route.js
- src/app/api/submitPaymentolduser/route.js
https://www.loom.com/share/353631094aca45ada6f5b65bdd68a0f7?sid=87d709d6-f198-4542-9c7b-ffb40c047bdd
Demo Video in the attached link.
> [Feature] Search Function work with HopeFuelID

- src/app/api/submitPayment/route.js
- src/app/api/submitPaymentolduser/route.js
submit transaction date would be in Thailand timezone.
> [enhancement] insert transaction in UTC +7 Thailand

- src/app/UI/AppBar/AppBar.js
- src/app/UI/Components/HopeIdStatus.js
- src/app/UI/ExtendUser/ExtendUser.js
- src/app/UI/ExtendUser/ExtendUserForm.js
- src/app/api/getCustomerFromCardID/route.js
- src/app/api/paymentDetails/route.js
- src/app/api/submitPaymentolduser/route.js
- src/app/api/updateNote/route.js
- src/app/entryForm/page.js
- src/app/extendUser/ExtendUserForm.js
- src/app/extendUser/page.js
- src/app/utilites/ExtendUser/checkPrfSubmit.js
- src/app/utilites/ExtendUser/extendUserSubmit.js
Make sure that extendUser Page is working properly....
onlly allow admin to more than one time.
> Extend user

- src/app/UI/AppBar/AppBar.js
> disable entryForm for emergency

- src/app/hopefuelidlist/components/HopeFuelIDListItem.js
- src/app/hopefuelidlist/page.js
@kaungphyowai I developed HopeFuelIDListItem components for item layout ticket no. of #127. Please kindly review my commit.
> Add: HopeFuelIDListItem components for item layout

- src/app/entryForm/page.js
@kaungphyowai, I have fixed the codebase alignment for ticket #133. Please check it and merge it into the development branch if there are no issues.
> Fix: adding screenshot url to the transaction data

- src/app/UI/Components/ActionButton.js
@kaungphyowai, I have fixed the codebase alignment for ticket #134. Please check it and merge it into the development branch if there are no issues.
> Fix: fixed taking wrong AgentId when confirming or denying the transaction

- src/app/api/searchDB/route.js
@kaungphyowai, I have fixed the codebase alignment for ticket #135. Please check it and merge it into the development branch if there are no issues.
> Fix: change the transaction asending sorting to desending

- src/app/UI/Components/ActionButton.js
@kaungphyowai, I have fixed the codebase alignment for ticket #136. Please check it and merge it into the development branch if there are no issues.
> Fix: Confirm and deny payment api is getting correct transaction ID instead of hopefuel id.

- src/app/entryForm/page.js
@kaungphyowai, I have fixed the codebase alignment for ticket #137. Please check it and merge it into the development branch if there are no issues.
> Fix: Add another argument for ActionButton called TransactionID

- src/app/UI/Components/CreatorInfo.js
- src/app/api/paymentDetails/route.js
@kaungphyowai, I have fixed the codebase alignment for ticket #138. Please check it and merge it into the development branch if there are no issues.
> Fix: AWS id is showing in the UI dashboard

- src/app/api/searchDB/route.js
@kaungphyowai, I have fixed the codebase alignment for ticket #139. Please check it and merge it into the development branch if there are no issues.
> Fix: showing 100 items in one wallet

- src/app/UI/Components/ItemCard.js
@kaungphyowai, I have fixed the codebase alignment for ticket #140 . Please check it and merge it into the development branch if there are no issues.
> Fix: ItemCard redirection

- src/app/UI/Components/GroupWallet.js
- src/app/search/page.js
@kaungphyowai, I have fixed the codebase alignment for ticket #141. Please check it and merge it into the development branch if there are no issues.
> Fix: page.js and groupwallet.js UI fix

- src/app/hopefuelidlist/components/HopeFuelIDListItem.js
- src/app/hopefuelidlist/page.js
- src/app/variables/const.js
@kaungphyowai I implemented sample UI for item component ticket no. of #128. Please kindly check.
> Add: sample UI for item component

- jest.config.js
- jest.setup.js
- package-lock.json
- package.json
I implemented 
- jest library setup in root folder
- update  mui library
- Add a command in `package.json` to execute test cases using Jest.
This is for issue #145 
@kaungphyowai
> [Test] testing setup with jest library

- src/app/hopefuelidlist/components/HopeFuelIDListItem.js
- src/app/hopefuelidlist/page.js
- src/app/variables/const.js
@kaungphyowai I implentend issue #132 for pagination infinite scroll. Please kindly reveiw. Thank you.
> add: test infinite scroll

- src/app/api/hopeFuelList/items/route.js
I implemented display current month data with attached data field  with pagination  , 
fetching default value **_page=1 and limit= 10_** data from DB .  @kaungphyowai 
_**Postman result**_
```json
{ "page":1,
"limit":1,
"data":[
{
"HopeFuelID":1,
"Name":"ကက",
"Email":"john@example.com",
"CardID":101,
"TransactionDate":"2025-02-01T02:55:00.000Z",
"Amount":100,
"CurrencyCode":"USD",
"Month":1,
"ScreenShot":"https://example.com/screenshot1",
"ManyChatId":"MANY123",
"FormFilledPerson":"AWS123",
"TransactionStatus":null,
"Note":"Customer requested refund"
}
]
}
```
I attached proposal issue for performance enhancement.
#148
> [Backend] Feature/143 display data api route for display current month hopefuellist

- package-lock.json
- package.json
- src/app/hopefuelidlist/page.js
@kaungphyowai Hello, Ko Dee. I installed and used use-debounce library to the project. Please kindly review this package.
> chore: install use-debounce library, and add useDebounce in page.js

- jest.config.js
- package.json
- src/app/api/hopeFuelList/search/__tests__/route.test.js
- src/app/api/hopeFuelList/search/route.js
- src/app/utilites/db.js
- teardown.js
I implemented 
- search API with status 200 for found case,400 for no search text,  404 for not found case, 500 for internal server error related with DB.
- update Jest config 
- unit testing for API Route
**Postman** 
_Not found case_ 
`q=kkkk ` kkk is not existed for current month in testing DB.
_found case_ 
`q=ကက`  ကက is existed for current month in testing DB.
> [Backend] 83 search api

- .github/workflows/CI_test.yml
- package.json
I implemented for continuous integration github yml file.
> [CI] 125 ci ci test for running testcase

- src/app/api/hopeFuelList/items/route.js
I implemented the bug fix for HopFuel List pagination .
**_Postman Result_** 
```json
{
"page": 2,
"limit": 5,
"data": [
{
"HopeFuelID": 9,
"Name": "nono",
"Email": "no@gmail.com",
"CardID": null,
"TransactionDate": "2025-02-20T02:46:31.000Z",
"Amount": 6000,
"CurrencyCode": "USD",
"Month": 1,
"ScreenShot": "",
"ManyChatId": "1",
"FormFilledPerson": "94b86498-0031-7049-bed4-3fbfec219a9b",
"TransactionStatus": "ဖောင်တင်သွင်းခြင်း",
"Note": "Extend Form"
},
{
"HopeFuelID": 10,
"Name": "hoho",
"Email": "hoho@gmail.com",
"CardID": null,
"TransactionDate": "2025-02-20T03:06:59.000Z",
"Amount": 8000,
"CurrencyCode": "USD",
"Month": 1,
"ScreenShot": "",
"ManyChatId": "1",
"FormFilledPerson": "94b86498-0031-7049-bed4-3fbfec219a9b",
"TransactionStatus": "ဖောင်တင်သွင်းခြင်း",
"Note": "Create User" …
```
> [Fix]  HopeFuel List API Page Parameter Parsing

- development.sql
- src/app/api/formOpenClose/route.js
I implemented the DB mysql script and form visibility api .
> Chore: add FormVisibilityStatus table

- .vscode/settings.json
- src/app/UI/AppBar/AppBar.js
- src/app/UI/Components/SubscriptionCard.js
- src/app/customerlist/components/CardDisplay.js
- src/app/customerlist/components/CardInfo.js
- src/app/customerlist/components/Sidebar.js
- src/app/customerlist/components/UserInfoCard.js
- src/app/customerlist/page.js
- src/app/hopefuelidlist/page.js
@kaungphyowai I implemented customer lists UI with sidebar and user info. Please kindly check Ko Dee.
> feat: customer list ui with sidebar and user info

- src/app/api/customers/route.js
I implemented  for the issue #254 .
The api with endpoint `api/customers?page={page}&limit={limit}`
**Postman result** 
**Default** Endpoint: `api/customers?page=1&limit=10` 
_**Postman result**_ 
Endpoint: `/api/customers?page=2&limit=3`
> Add: customer list with pagination

- development.sql
- src/app/api/customers/[id]/edit/history/route.js
- src/app/api/customers/[id]/editHistory/route.js
There is no issue ticket for this implementation. Just FYI, @yaungnilinn, I implemented it because it is part of this sprint's user story.
**_Postman request_**
I also attached the UI in order for tracking the user story.
> [API] Fetching Customer history log

- src/app/api/hopeFuelList/details/[id]/subscription/route.js
> Add: hopeFuel subscription card api

- src/app/api/customers/[id]/route.js
- src/app/api/customers/route.js
I implemented for the issue #255 
**_Postman result_**
> Add: customer detail api is added

- development.sql
This ManyChat Schema will be used for the business logic related with ManyChat .
> [DB] Many Chat db schema is added 

- src/app/createForm/extendForm.js
I add dynamic error messages for form submission .
> Chore: Dynamic error message for Extend user validation UI

- src/app/createForm/createForm.js
This PR introduces **form validation improvements** to ensure users cannot submit the form with missing fields. It includes:
- **Error handling for required fields**
- **Real-time validation for ManyChatId (numeric)**
- **File upload validation (screenshots required)**
- **UI feedback for validation errors**
---
[![Watch the Video](https://cdn.loom.com/sessions/thumbnails/be932ca4544b4f46a70af45d78b3ad8e-e46d6e1dd82b9d33-full-play.gif)](https://www.loom.com/share/be932ca4544b4f46a70af45d78b3ad8e)
> _Click on the thumbnail above to watch the video walkthrough._
---
- **Prevent form submission if required fields are missing**
- **Error messages appear dynamically for validation**
- **ManyChatId now strictly accepts numeric values**
- **Ensures screenshot upload before submission**
- …
> Chore : Create form validation

- src/app/createForm/createForm.js
I implemented the form validation for the field => Wallet, Currency and Photo .
This time, I use useCallBack hook to make sure for the validation from the frontend.
> Chore: Field wallet currency create form

- src/app/createForm/extendForm.js
I implemented the Form validation for the field wallet, currency and photo
This form is applied for existed user .
> Chore: Wallet,Currency,Photo validation is added

- src/app/extendUser/ExtendUserForm.js
> Chore: Wallet,Currency ,photo validation is added

- src/app/createForm/checkUser.js
- src/app/extendUser/page.js
- src/app/formopenclose/components/FormStatus.js
- src/app/formopenclose/page.js
@kaungphyowai I implemented and integrated api for admin open close form status ticket no. of #207. Please kindly check Ko Dee. Thanks
> integrate: admin form open close api

- src/app/api/customers/[id]/edit/history/route.js
- src/app/api/formOpenClose/route.js
> Chore: delete export for build error

- src/app/api/customers/search/route.js
I implemented the searching API for the CustomerList applying partial matching for the field Name, Email, HopeFuelID, MemberCardID, ManyChatID for the sprint _26/2/2025_.
`API response for missing search term `
`API response for searchTerm`
> Add: Search api customer list

- src/app/api/v1/fundraisers/route.js
This PR introduces a small patch for the creation of fundraising organizations under the /api/v1/fundraisers route. It does not cover the full user story for organization creation but addresses a specific part of the implementation.
for the successful creation , status => 201
For the invalid field , status => 400
> API: Create fundraiser api

- src/app/api/customers/[id]/edit/history/route.js
- src/app/api/customers/[id]/edit/route.js
**Postman Result**
There will be two response for editing customer's log.
Before changing the customer's field ,
After changing the customer's field,
> Add: create customer edit history

- src/app/UI/Sidebar.js
- src/app/UI/SidebarNav.js
- src/app/layout.js
I implemented the SideBar UI as HopeFuel's Nav Bar.
This is the [**Demo video**](https://www.loom.com/share/4b636e5ea4f6457fa648e088bac238e5?sid=f99cbdfd-055c-46c0-b602-22b98daf8d32) .
> FrontEnd: Side Bar Nav UI is added as Nav Bar 

- src/app/customerlist/components/CardInfo.js
- src/app/customerlist/components/EditHistory.js
- src/app/customerlist/components/Sidebar.js
- src/app/customerlist/components/UserInfoCard.js
- src/app/customerlist/page.js
@kaungphyowai I implemented customer list api ticket no. of #253.
> integrate: customer list and details by id api

- package-lock.json
- package.json
- src/app/api/countries/route.js
- src/app/api/v1/fundraisers/route.js
- src/app/fundraisers/components/BaseCountry.js
- src/app/fundraisers/components/LogoUpload.js
- src/app/fundraisers/components/fundraisingForm.js
- src/app/fundraisers/create/page.js
- src/app/fundraisers/schema.js
- src/app/utilites/createForm/fileHandler.js
@akm-coding  @kaungphyowai @thumin-dev please kindly review the unfinished small patch of create fundraiser form.
[Demo Video ](https://www.loom.com/share/ed6905b5762e41348b0196f25cdc2b78?sid=da19c4e5-e618-47e7-a70e-c7ab5f7f2b94)
> Integrate: Base country fundraiser frontend to the server

- src/app/customerlist/components/CustomerInfoEdit.js
- src/app/customerlist/components/EditHistory.js
- src/app/customerlist/components/UserInfoCard.js
- src/app/customerlist/page.js
@kaungphyowai @aye-nyeinSan @thumin-dev  I integrated customer list edit history api. Please kindly review.
> Integration customer list api

- development.sql
@kaungphyowai I add database schema for fundraiser management. Please check Ko Dee.
> add: fundraiser management database schemas

- src/app/api/customers/[id]/edit/route.js
there is a build error due to export to the build functions.
> Fix: Build error Due to export

- src/app/api/v1/fundraisers/route.js
@kaungphyowai @aye-nyeinSan @thumin-dev I developed get fundraisers api ticket no. of #294. Please kindly check.
> feat: develop get all fundraisers api

- development.sql
I added the Minimum Amount Schema.
> add: minimum amount schema

- src/app/api/v1/exchange-rates/[id]/route.js
- src/app/api/v1/exchange-rates/route.js
I added CRUD APIs for exchange rate management. Please kindly review and give me feedback.
I also added two validation.
1. One currency can only have one exchange rate.
2. Update API only allows to update the exchange rate (cannot update currency and base country).
Create API
Get all API
Get by Id API
Update by Id API
Delete by Id API
> API: exchange rates CRUD APIs

- src/app/api/v1/minimum-amount/[id]/route.js
- src/app/api/v1/minimum-amount/route.js
I added CRUD APIs for minimum amount management. Please kindly review and give me feedback.
Create API
Get All API
Get by Id API
Update API
Delete API
> Add: minimum amount CRUD APIs

- src/app/UI/SidebarNav.js
- src/app/components/Modal.js
- src/app/fundraisers/@modal/create/page.js
- src/app/fundraisers/@modal/default.js
- src/app/fundraisers/components/fundraisingForm.js
- src/app/fundraisers/create/page.js
- src/app/fundraisers/layout.js
- src/app/fundraisers/page.js
Demo View
https://www.loom.com/share/9d91c703379e4ce7ac7fd35a0070404c?sid=0c7dba67-7b9e-4055-9bc0-142f7144c334
> Update: Make FormModel Overlay

- development.sql
Fundraiser_ContactLinks is joined with PlatformID in Platform Database table .
> [DB Schema] : Db platform schema

- src/app/api/v1/fundraisers/create/route.js
- src/app/fundraisers/@modal/create/page.js
- src/app/fundraisers/components/AcceptedCurrency.js
- src/app/fundraisers/components/BaseCountry.js
- src/app/fundraisers/components/fundraisingForm.js
- src/app/fundraisers/schema.js
Fundraiser ID by Central Database , implemented backend, API binding and UI.
> ADD: Fundraiser central ID Form Field 

- development.sql
- src/app/api/v1/fundraisers/details/[id]/route.js
@kaungphyowai @thumin-dev @aye-nyeinSan I implemented fundraiser details api with id ticket no. of #298  and #301. Please kindly review.
API testing
> feat: develop fundraiser detail api with id

- src/app/api/customers/route.js
I fix the sql query return for customer api.
> [Bug ] custmers api not return

- src/app/components/Button.js
- src/app/createForm/checkUser.js
- src/app/createForm/page.js
updated ui for check user in form create
> update ui for check user

- src/app/components/Button.js
- src/app/components/Dropzone.js
- src/app/components/Input.js
I created reusable component for input box and dropzone
> Add: create reusable component for input and dropzone

- src/app/fundraisers/components/FundraiserCard.js
- src/app/fundraisers/components/FundraiserDetails.js
- src/app/fundraisers/page.js
@kaungphyowai @aye-nyeinSan @thumin-dev I integrated fundraiser details api ticket no. of #299. Please kindly review.
> integrate: fundraiser details api

- src/app/UI/SidebarNav.js
- src/app/admin-panel/exchange-rates/page.js
- src/app/admin-panel/page.js
I structured a UI for exchange rate management.
> Add: exchange rates management ui

- src/app/createForm/checkUser.js
- src/app/createForm/createForm.js
- src/app/utilites/createForm/createformSubmit.js
- src/app/utilites/createForm/fileHandler.js
I updated the ui and add some features.
> feature: new ui and api integration for membership registration form

- src/app/components/Button.js
- src/app/fundraisers/page.js
@kaungphyowai @aye-nyeinSan @thumin-dev I integrated delete fundraiser api ticket no. of #302 #303 #305. Please kindly review.
> integrate: delete fundraiser api

- src/app/createForm/createForm.js
> fix: dropzone import naming

- src/app/api/v1/exchange-rates/get-by-currency-id/route.js
- src/app/createForm/createForm.js
- src/app/utilites/createForm/createformSubmit.js
- created new api to get exchange rate by currency
- integrated exchange rates in ui
> Feature/membership form UI

- src/app/api/v1/fundraisers/update/[id]/route.js
- src/app/fundraisers/[id]/edit/page.js
- src/app/fundraisers/components/FundraisingForm.js
- src/app/fundraisers/components/LogoUpload.js
- src/app/fundraisers/page.js
I implemented the API+UI for fundraiser update Form . 
**Postman API**
**UI**
> Update fundraiser form

- src/app/fundraisers/page.js
@kaungphyowai @aye-nyeinSan @thumin-dev I developed search bar and search by name and id. ticket no. of #291 and #296
> feat: search fundraiser by name and id

- src/app/api/v1/minimum-amount/check-minimum-amount/route.js
- src/app/createForm/createForm.js
- src/app/createForm/page.js
- src/app/utilites/createForm/createformSubmit.js
- added error handling in API call (createformSubmit.js) (f1e2f4e)
- added new api to check minimum amount real-time when component mount (a38e9d8)
- added success modal in parent page (0b176fd)
> refactor with error handling the membership form

- src/app/admin-panel/exchange-rates/page.js
- src/app/components/Input.js
updated input in admin exchange rate with custom input component
> chore: update input with custom input component

- src/app/paymentCheck/page.js
I add validation for Array check in row map and fix the setData state
> fix: add validation for Array check in setData row map

- package-lock.json
- package.json
- prisma/schema.prisma
I added a new package for migration (prisma)
> add: new package prisma migration

- .github/workflows/deploy.yml
I'm testing the ci cd pipeline here.
> feat: add ci/cd pipeline to run migration and deploy

- .github/workflows/deploy.yml
I comment off the status check for the first time migration.
> chore: comment off status check

- prisma/migrations/20250421035553_add_fk_in_customer_to_country/migration.sql
- prisma/schema.prisma
I added foreign key to join table between customer and base country. please kindly check.
> add: new migration for table join (customer <---> basecountry)

- src/app/api/v1/fundraisers/create/route.js
- src/app/fundraisers/[id]/edit/page.js
- src/app/fundraisers/components/FundraisingForm.js
- src/app/fundraisers/layout.js
- src/app/fundraisers/page.js
- src/app/fundraisers/schema.js
I fixed the bug that can't create fundraiser both frontend and backend. Please kindly check.
> fix: create fundraiser api route

- src/app/api/customers/route.js
- src/app/api/customers/search/route.js
- src/app/customerlist/page.js
I fixed the bug that can't search in customer api.
> fix: customer management get, and search api

- src/app/UI/SidebarNav.js
- src/app/api/submitPayment/route.js
I added a country field in submit payment api
> chore: add country field in submitPayment api

- src/app/api/customers/[id]/route.js
- src/app/customerlist/components/CustomerInfoEdit.js
- src/app/customerlist/components/UserInfoCard.js
- src/app/customerlist/page.js
I fixed the issue ticket no [#395](https://github.com/i4BSolutions/hope-fuel/issues/395).
Admin can edit the user country.
This fixed is also done for backlog ID 20's issue ticket [#421](https://github.com/i4BSolutions/hope-fuel/issues/421) and [#418](https://github.com/i4BSolutions/hope-fuel/issues/418)
> fix: basecountry table join and update basecountry

- src/app/UI/SidebarNav.js
- src/app/customerlist/components/UserInfoCard.js
- src/app/customerlist/page.js
I fixed the issue ticket no [#396](https://github.com/i4BSolutions/hope-fuel/issues/396)
> chore: disable the customer edit button if role is not admin

- src/app/api/v1/exchange-rates/route.js
- src/app/api/v1/fundraisers/route.js
- src/app/fundraisers/components/FundraiserCard.js
- src/app/fundraisers/components/FundraiserDetails.js
- src/app/fundraisers/page.js
I add accepted currencies and base country name to the fundraisers api.
> feat: add accepted currencies and base country name to the fundraisers list api

- src/app/fundraisers/components/FundraiserDetails.js
> fix: TC042 contact links open in new tab

- src/app/createForm/createForm.js
- src/app/createForm/page.js
> Bug fix/issue#232

- src/app/fundraisers/page.js
I add filter function to fundraiser page.
> feat:TC037 add filtering function to filter fundraisers

- src/app/api/v1/minimum-amount/check-minimum-amount/route.js
- src/app/createForm/components/errorMessage.js
- src/app/createForm/createForm.js
- src/app/createForm/page.js
- src/app/customerlist/components/CustomerInfoEdit.js
- src/app/customerlist/page.js
- fix validation check in create form for new user
- make functioning decline button
> Bug fix/issue#410#414

- .github/workflows/deploy.yml
I removed the pull request trigger to only run ci cd when changes are merged into development branch.
> chore: remove pull request trigger in deploy.yml

- package-lock.json
- package.json
- src/app/admin-panel/csv/page.js
- src/app/admin-panel/exchange-rates/page.js
- src/app/admin-panel/page.js
- Developed the date range picker #378 
- Developed the export button #379
> feat: export csv ui

- src/app/admin-panel/csv/page.js
- developed export csv confirm modal #380
> feat: export csv confirmation modal

- src/app/createForm/createForm.js
- src/app/createForm/extendForm.js
- src/app/createForm/page.js
- src/app/utilites/extendForm/extendFormSubmit.js
I changed the ui for extending old user to align with the new user registration.
> chore: update ui for extend user page

- src/app/api/InCustomerTable/route.js
- src/app/createForm/extendForm.js
I added user country table join in sql to fetch user details.
> chore: add user country in get api

- src/app/createForm/extendForm.js
- src/app/createForm/extendOrNot.js
- src/app/extendUser/ExtendUserForm.js
I refactored the extend form with card id page by removing unnecessary codes.
> chore: refactor the extend form with card id page

- package-lock.json
- package.json
I added day js package in package.json
> add: dayjs package

- src/app/UI/Components/TransactionList.js
- src/app/admin-panel/csv/page.js
- I developed transaction list table ui.
> feat: transaction list table ui

- src/app/api/transactions/export-confirm-payments/route.js
- src/app/utilites/prisma.js
I added new api for csv export data.
> add: new api for csv export data fetch

- src/app/api/paymentDetails/route.js
- src/app/api/searchDB/route.js
- src/app/entryForm/page.js
- src/app/search/page.js
I fixed the bug in payment check view.
1. search with hope id
2. search with wallet selection
3. details view
> fix: search by hope id and wallet selection

- src/app/UI/Components/TransactionList.js
- src/app/admin-panel/csv/page.js
- I integrated transaction complete api #383 
- I integrated export and updated records api #384
> integrate: transaction list api for csv export

- src/app/admin-panel/csv/page.js
- I implemented CSV download logic ticket no. of #385
> feat: add export csv file function

- src/app/admin-panel/csv/page.js
- Fix transaction status before export csv file
> fix: export csv file logic transaction status

- src/app/UI/Components/ItemList.js
- src/app/api/searchDB/route.js
- src/app/search/page.js
I added proper pagination handling in the search api and payment check view
> fix: add proper pagination in api and frontend

- src/app/createForm/createForm.js
> fix: make donor country required and disable the username and email

- prisma/schema.prisma
- src/app/admin-panel/csv/page.js
- src/app/api/transactions/export-confirm-payments/route.js
- Refactor csv export transaction list api
> refactor: csv export transactions list api

- prisma/schema.prisma
- src/app/UI/Components/SubscriptionCard.js
- src/app/UI/SidebarNav.js
- src/app/api/searchDB/route.js
- src/app/extendUser/ExtendUserForm.js
- src/app/extendUser/page.js
- src/app/hopefuelidlist/components/HopeFuelIDListDetails.js
- src/app/hopefuelidlist/components/HopeFuelIDListItem.js
- src/app/hopefuelidlist/components/ImageCarousel.js
- src/app/hopefuelidlist/page.js
- src/app/libs/FormatAmount.js
- Hopefuel ID List
- Updated list view details
- Fixed unexpected behavior with loading states
- Updated image modal for better UX
- Added UI for "Note" in detail modal
- Extend Form
- Allowed admins to extend form regardless of the form state
- Fixed UI fluctuations
- Updated typo in prisma schema
> UI updates

- src/app/UI/Components/ActionButton.js
- src/app/UI/Components/ItemCard.js
- src/app/api/confirmTransaction/route.js
- src/app/api/deniedTransaction/route.js
- src/app/api/searchDB/route.js
- src/app/entryForm/[HopeFuelID]/page.js
- src/app/entryForm/page.js
- src/app/search/page.js
I refactored overall pages and function including in payment check view.
Make components more effective by use parent, child relation.
> fix: refactor overall pages and function in payment check view

- src/app/UI/Components/TransactionsHistoryList.js
- src/app/admin-panel/csv/page.js
- src/app/components/Button.js
- I implemented export transaction history ui.
> feat: csv export transaction history ui

- src/app/admin-panel/csv/page.js
- src/app/utilites/exportCSV/csvHandler.js
I added csv file handler function to upload generated csv file on s3 bucket
> add: csv file handler to upload csv file on s3

- src/app/UI/Components/TransactionsHistoryList.js
- src/app/admin-panel/csv/page.js
- src/app/customerlist/components/Sidebar.js
- src/app/customerlist/page.js
- I implemented and integrated csv logs history api, and download logic.
> integrate: csv logs api and file download logic

- src/app/fundraisers/page.js
- I fixed filter currency and country in customer page.
> fix: filter country and currency customer page

- src/app/api/customers/search/route.js
- I implemented customer search api and fixed query.
> refactor: customer search api

- src/app/components/Dropzone.js
- src/app/createForm/createForm.js
- src/app/utilites/createForm/createformSubmit.js
- src/app/utilites/createForm/fileHandler.js
I wrote a function to delete screenshot from s3 bucket.
> fix: delete screenshot from s3

- src/app/customerlist/page.js
- I implemented card issued ui
> feat: add card issued in customer page

- src/app/UI/Components/SubscriptionCard.js
- src/app/customerlist/page.js
> fix: padding issue

- src/app/customerlist/page.js
Refactoring customer list page
- customer detail error handling
- customer search error handling
> refactor: customer list page

- src/app/createForm/extendForm.js
- src/app/utilites/extendForm/extendFormSubmit.js
i added screenshot delete button function in extend form
> fix: add screenshot delete function in extend form

- src/app/hopefuelidlist/page.js
- Integrated subscription api in hope fuel details
> integrate: subscription api in hope fuel details

- src/app/UI/Components/ActionButton.js
- src/app/api/deniedTransaction/route.js
- src/app/utilites/calculateExpireDate.js
I refactored the whole payment deny api. Please check.
> fix: refactor the payment deny api

- src/app/customerlist/components/CardDisplay.js
- src/app/customerlist/page.js
- I integrated card issued api.
> integrate: card issued api

- src/app/UI/Components/CardIssuedList.js
- src/app/UI/Components/GroupWallet.js
- src/app/api/searchDB/route.js
- src/app/entryForm/components/searchList.js
I added all wallet filter in payment check view page and api.
> feat: add all wallet filter

- src/app/api/customers/search/route.js
- src/app/customerlist/components/Sidebar.js
- src/app/customerlist/page.js
- Fixed customer list search api
> hotFix: customer list search api

- src/app/admin-panel/_components/dashboard/PaymentCheckerStats.jsx
I integrated the transaction status api in PaymentStatsCard.jsx.
> integrate: transaction status api bind

- src/app/admin-panel/_components/dashboard/PaymentCheckerStats.jsx
- src/app/admin-panel/_components/dashboard/_components/WalletGrid.jsx
- src/app/admin-panel/_components/dashboard/_components/WalletMultiSelect.jsx
I created new component for multiple wallet selection.
> add: multi wallet selection ui

- prisma/migrations/20250516035517_add_assigned_wallets_table/migration.sql
- prisma/schema.prisma
I added new table for assigned wallet feature.
> add: assigned wallet table

- src/app/admin-panel/_components/dashboard/HopefuelIdStats.jsx
- src/app/admin-panel/_components/dashboard/SupportAgentStats.jsx
- src/app/admin-panel/_components/dashboard/_components/FormFillingAgentRateTable.jsx
- src/app/admin-panel/_components/dashboard/_components/HopeFuelIDStatusChart.jsx
- src/app/api/agent/transaction-status/route.js
I integrated form fill agent rates api.
> integrate: form fill agent rates api to frontend

- src/app/admin-panel/_components/assign-dashboard/_components/GroupAssign.jsx
- src/app/admin-panel/_components/assign-dashboard/_components/WalletAssign.jsx
- src/app/admin-panel/_components/assign-dashboard/page.jsx
- src/app/admin-panel/page.jsx
- src/app/api/v1/wallets/assigned-wallets/route.js
I added assign dashboard UI components.
> Feature/assign dashboard UI components

- src/app/api/v1/wallets/assigned-wallets/route.js
> add: assign wallet apis

- prisma/schema.prisma
> Fix: customer email schema in prisma

- src/app/admin-panel/_components/dashboard/HopefuelIdStats.jsx
- src/app/admin-panel/_components/dashboard/SupportAgentStats.jsx
- src/app/admin-panel/_components/dashboard/_components/FormFillingAgentRateTable.jsx
- src/app/admin-panel/_components/dashboard/_components/HopeFuelIDStatusChart.jsx
- I made a responsive ui for agent rates table and hope id stats.
> fix: responsive ui agent rates and hope id stats

- prisma/migrations/20250520060900_add_agentid_to_agentgroup/migration.sql
- prisma/migrations/20250520070852_agent_group_many_to_many/migration.sql
- prisma/schema.prisma
- src/app/api/agent/agent-group/route.js
I developed assign agents group api POST and GET methods.
- api/agent/agent-group (POST)
`{
"status": 201,
"message": "Agent(s) group assigned successfully.",
"data": {
"group": {
"AgentGroupID": 1,
"GroupName": "Group A"
},
"assignedAgents": [
{
"AgentId": 1,
"Username": "Agent Mg Mg"
},
{
"AgentId": 2,
"Username": "Agent Aung Aung"
},
{
"AgentId": 8,
"Username": "yaungni"
},
{
"AgentId": 3,
"Username": "Agent Ko Ko"
}
]
}
}`
- api/agent/agent-group (GET)
`{
"status": 200,
"message": "Assigned agent groups retrieve successfully.",
"data": {
"result": [
{
"AgentGroupID": 1,
"GroupName": "Group A",
"AssignedAgents": [
{
"AgentId": 1,
"Username": "Agent Mg Mg"
},
{
"AgentId": 2,
"Username": "Agent Aung Aung"
},
{
"AgentId": 3,
"Username": "Agent Ko Ko"
},
{
"AgentId": 8,
"Username": …
> feat: assingn agents api and AssignedAgent table in schema

- src/app/admin-panel/_components/assign-dashboard/_components/GroupAssign.jsx
- src/app/admin-panel/_components/dashboard/HopefuelIdStats.jsx
- src/app/admin-panel/_components/dashboard/SupportAgentStats.jsx
- src/app/admin-panel/_components/dashboard/_components/FormFillingAgentRateTable.jsx
- src/app/admin-panel/_components/dashboard/_components/HopeFuelIDStatusChart.jsx
- src/app/api/agent/agent-group/route.js
- I integrated agent group api
> integrate: agent group api

- src/app/admin-panel/_components/assign-dashboard/_components/GroupAssign.jsx
- I fix api refetch call in useEffect
> chore: refetch api call in useEffect

- src/app/components/Input.js
- src/app/createForm/checkUser.js
- src/app/createForm/createForm.js
- src/app/createForm/page.js
- src/app/utilites/createForm/createformSubmit.js
Refactored the create form page by converting to a react form hook.
> refactor: change to react form hook

- prisma/migrations/20250524034239_add_from_to_in_csv_logs_table/migration.sql
- prisma/schema.prisma
Added new column from date and to date in csv export transactions logs table.
> feat: add new column from to in csv export logs table

- prisma/migrations/20250526062806_add_follow_up_status_table/migration.sql
- prisma/migrations/20250526073926_add_customer_follow_up_status_table/migration.sql
- prisma/schema.prisma
- prisma/seed.js
I added new table schema for follow up status feature.
> feat: new table for follow up status

- src/app/admin-panel/_components/role-management/page.jsx
- src/app/admin-panel/page.jsx
- I developed role management.
> feat: role management ui

- src/app/api/agent/agents/route.js
- src/app/api/agent/roles/route.js
- I implemented role management api.
> feat: role management api

- src/app/admin-panel/_components/dashboard/CustomerStats.jsx
- src/app/admin-panel/_components/dashboard/_components/CustomerCard.jsx
- src/app/admin-panel/_components/dashboard/_components/CustomerFollowUpModal.jsx
- src/app/admin-panel/_components/dashboard/_components/StatusDropdown.jsx
- src/app/admin-panel/_components/dashboard/_components/StatusFilter.jsx
> feat: customer follow up modal with mock data

- src/app/api/checkPermission/route.js
- src/app/api/checkUser/route.js
- src/app/api/checkolduserpermission/route.js
- src/app/api/createNewUser/route.js
- src/app/api/getManyChatID/route.js
- src/app/api/getUserId/route.js
- src/app/api/loadWallet/route.js
> Airtable for production

- src/app/UI/Components/TransactionList.js
- src/app/admin-panel/_components/exportCsv/page.jsx
- src/app/api/transactions/export-confirm-payments/route.js
Added form filled agent name and note in csv export table
> chore: add form filled agent and note in csv export

- prisma/migrations/20250715022412_add_nullable_in_fundraiser_email/migration.sql
- prisma/schema.prisma
- src/app/api/v1/fundraisers/create/route.js
- src/app/fundraisers/_components/FundraisingForm.js
- src/app/fundraisers/schema.js
Fundraiser Email
Fixed the table to make fundraiser email nullable.
> fix: add nullable on fundraiser email field

- src/app/createForm/createForm.js
- src/app/createForm/extendForm.js
ID - 171
Change 'Amount' Label to 'Currency'
> fix: change amount to currency in form label

- src/app/api/transactions/wallet-summary/route.js
ID-153
Exclude the denied transaction count in wallet summary dashboard
> fix: exclude the denied transaction count in wallet summary dashboard

- src/app/api/submitPayment/route.js
- src/app/entryForm/components/paymentDetails.js
ID - 134
Let the payment checker update note even if empty when created
> fix: let the payment checker to update note even if N/A

- src/app/api/v1/wallets/assigned-wallets/get-by-agent-id/route.js
ID-204
Incorrect Hope ID count in Payment Check View wallets
> fix: wallet count on payment check page

- src/app/createForm/extendForm.js
fix: add form loading in extend form
> Bug Fix(v2.1.0.10)
